In [2]:
import numpy as np

In [16]:
c =  np.zeros(5)
print(c)
type(c)


[0. 0. 0. 0. 0.]


numpy.ndarray

In [18]:
print(c.shape)
print(c.dtype)

(5,)
float64


In [20]:
d= np.zeros(shape=(5,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
e = np.ones(5)
print(e)
print(e.dtype)

[1. 1. 1. 1. 1.]
float64


In [28]:
t = (5,3)
f = np.ones(t,dtype=int)
print(f)
print(f.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
int32


In [34]:
g=np.empty((3,2))
print(g)
print(g.dtype)

[[1. 0.]
 [0. 1.]
 [0. 0.]]
float64


In [35]:
h = np.eye(3)
print(h)
print(h.shape,h.dtype)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3) float64


In [36]:
h = np.eye(3,2)
print(h)
print(h.shape,h.dtype)

[[1. 0.]
 [0. 1.]
 [0. 0.]]
(3, 2) float64


In [38]:
# numpy.linspace(시작값, 끝값, num=요소개수) # : 시작값부터 종료값까지 요소갯수 만큼 균등한 값으로 배정
i = np.linspace(1,4,5)
print(i)
print(i.shape,i.dtype)

[1.   1.75 2.5  3.25 4.  ]
(5,) float64


In [40]:
# numpy.arange(): arange(시작값, 종료값, 간격)
j = np.arange(5)
print(j)
print(j.dtype)

[0 1 2 3 4]
int32


In [42]:
j= np.arange(5,20,3)
print(j)

[ 5  8 11 14 17]


In [44]:
j = np.arange(5,20,15)# 간격이 크면 앞에 한개만 print
print(j)

[5]


In [45]:
np.arange(24).reshape(2,3,4) # 2면, 3행, 4열(0~23까지를 2면 3행 4열로 재배열)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
a = np.float32(5)
print(a)
print(type(a))

5.0
<class 'numpy.float32'>


In [50]:
b = np.arange(5)
print(b)
print(type(b))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [53]:
c = np.uint16([1,25,8, 0, -1, -2, 65534, 65535, 65536 ])
print(c)
print(type(c))
print(c.shape)
print(c.dtype)



[    1    25     8     0 65535 65534 65534 65535     0]
<class 'numpy.ndarray'>
(9,)
uint16


In [54]:
arr1= np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
print(arr1[2])
print(arr1[:5])
print(arr1[0:5])
print(arr1[0:5:1])
print(arr1[:2])
print(arr1[::2])
print(arr1[::3])
print(arr1[1:7:2])

2
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1]
[0 2 4 6 8]
[0 3 6 9]
[1 3 5]


In [69]:
print(arr1[:-1])
print(arr1[::-1])
print(arr1[-3:6])
print(arr1[-1::])
print(arr1[-2:])
print(arr1[-6:3:-1])


[0 1 2 3 4 5 6 7 8]
[9 8 7 6 5 4 3 2 1 0]
[]
[9]
[8 9]
[4]


In [70]:
arr2 = np.arange(9).reshape(3,3) 

In [73]:
arr = np.array([[1,2,3],[4,5,6]],dtype ='int32')
print(arr)
print()

[[1 2 3]
 [4 5 6]]



In [77]:
print('sum: ',arr.sum())
print('shape: ',arr.shape);print()

sum:  21
shape:  (2, 3)



In [79]:
print("axis =0",arr.sum(axis=0));print() #세로(열)방향으로 더함
print("axis = 1",arr.sum(axis=1));print() #가로(행)방향으로 더함

axis =0 [5 7 9]

axis = 1 [ 6 15]



In [82]:
arr = np.array([1,3,5,7])
for i in arr:
    print(i)

1
3
5
7


In [86]:
arr = np.arange(8).reshape(4,2)
print(arr,'\n')
for i in arr:
    print(i)


[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[0 1]
[2 3]
[4 5]
[6 7]


In [87]:
arr = np.arange(8).reshape(4,2)
print(arr,'\n')
for a,b in arr:
    print(a+b,'\t',a*b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

1 	 0
5 	 6
9 	 20
13 	 42


In [88]:
np.random.rand(5)

array([0.08119066, 0.72649991, 0.10987451, 0.25109323, 0.88284844])

In [89]:
np.random.randint(5,size=10)

array([1, 0, 2, 3, 2, 1, 4, 2, 1, 4])